### PR TITLE
add package: php

### PR DESCRIPTION
**Pull request by notona**
a popular General purpose scripting language.

I can't use stable release of php. stable version of php is 5.6.
but php 5.6 needs bison 2.6 to build. so i  used RC version to build..

### CODE REVIEW

**Comment by mingwandroid** [comment]
Would this not be better in MINGW-packages

**Comment by notona** [comment]
oh sorry. that is better i think.

i will move to this pull request to MINGW-packages repository

thanks.

**Comment by notona** [comment]
@mingwandroid 

i have built test as MINGW-packages, but an unknown errors has occured.
so i wound like to this pull request again.

thank you for making the time to this matter.

**Comment by Alexpux** [comment]
Sorry but we don't want to have PHP as MSYS package. MSYS2 is designed for developing MINGW applications in first place. If you want PHP as Unix application you seems want to install Cygwin but not MSYS2

**Comment by notona** [comment]
okay. i understand.

thanks!

**Comment by muv1** [comment]
https://github.com/msys2/MSYS2-packages/issues/322

**Pull request closed without merging**
