### PR TITLE
ngspice

### PR DESCRIPTION
**Pull request by orsonmmz**

### CODE REVIEW

**Comment by Alexpux** [comment]
Don't want to see it in msys-packages.

**Comment by orsonmmz** [comment]
Hi Alexpux,

Is there any particular reason for your decision? Is it the software itself or the PKGBUILD file seems wrong to you?

**Comment by orsonmmz** [comment]
Should I move it to mingw packages?

**Comment by Alexpux** [comment]
MSYS packages is set of packages to help developing native mingw-w64 packages . MSYS2 is not cygwin and I don't want to increase msys packages count without very good reason.

**Comment by Alexpux** [comment]
You can try to build it with mingw.

**Comment by orsonmmz** [comment]
Ok, sorry for the noise

**Pull request closed without merging**
