### PR TITLE
added perl-Date-Calc perl-Encode-compat perl-ExtUtils-MakeMaker perl-…

### PR DESCRIPTION
**Pull request by smartmarmot**
…List-MoreUtils perl-Math-Int64 perl-Test-Harness perl-Carp-Clan

### CODE REVIEW

**Comment by smartmarmot** [comment]
I think there is a wrong configuration serverside as the perlapi./h missing is available within:
$ pacman -Qo /usr/lib/perl5/core_perl/CORE/perlapi.h
/usr/lib/perl5/core_perl/CORE/perlapi.h is owned by perl 5.22.1-1

**Comment by mati865** [comment]
Don't worry about the bots, they are buggy.
If it does compile in fresh msys2 everything is ok.

**Comment by Alexpux** [comment]
I see issues with building List-MoreUtils and Math-Int4. Also CPAN-Meta not needed as it part of perl package.

**Comment by smartmarmot** [comment]
Thank you for the feedback, as far I can see the Math-Int64 require for testing the ExtUtils::MakeMaker  . I think the error is due to that, I'll fix the PKGBUILD adding the depends=('perl-ExtUtils-MakeMaker').
I will check the issue with the List-MoreUtils module.

**Comment by Alexpux** [comment]
Errors is due to linking to perl library

**Comment by smartmarmot** [comment]
Ok then I need to double-check can you remove just the broken packages?

**Comment by smartmarmot** [comment]
otherwise please revert the merge I don't want to block you with this issue

**Comment by Alexpux** [comment]
I'm upload packages that build successfully, others need to fix

**Comment by smartmarmot** [comment]
pefect thanks!

**Pull request merged**
