### PR TITLE
ruby 2.5.0 - Update to latest version.  Rekey patches.  Added one fro…

### PR DESCRIPTION
**Pull request by JPeterMugaas**
…m libffi for a built in version just in case that was compiled.

### CODE REVIEW

**Comment by Alexpux** [comment]
@JPeterMugaas 32-bit packages fail to build

**Comment by JPeterMugaas** [comment]
What error did you get?

**Comment by Alexpux** [comment]
Read my comment carefully. I post error

**Comment by JPeterMugaas** [comment]
Sorry, I was reading it from Outlook and I didn't see it.

**Comment by JPeterMugaas** [comment]
I think it could be related to this: https://github.com/colszowka/simplecov/issues/652#issuecomment-362436552 or this https://bugs.ruby-lang.org/issues/14334 .  It does not seem to effect MSYS2 64-bit though.

**Comment by Alexpux** [comment]
Patch from bug report doesnt solve problem

**Pull request merged**
