### PR TITLE
Install OK if no info, fix bashisms

### PR DESCRIPTION
**Pull request by achadwick**
(Name of branch because I first spotted it with `gmp`)

Made things less functionally dependent on info even if they declare no dependency on it.

Fixed a bashism that hist related lines.

### CODE REVIEW

**Comment by achadwick** [comment]
Whups, didn't bump pkgver so no checks ran. I'll just fix up those commits... :flushed:

**Comment by achadwick** [comment]
Not me! I didn't break it, guv'nor! At least, not with _those_ commits :neutral_face: 

```
/usr/include/time.h:210:5: error: unknown type name ‘clockid_t’
 int _EXFUN(clock_nanosleep,
     ^
/usr/include/time.h:285:5: error: unknown type name ‘pid_t’
 int _EXFUN(clock_getcpuclockid, (pid_t pid, clockid_t *clock_id));
     ^
/usr/include/time.h:285:5: error: unknown type name ‘clockid_t’
 int _EXFUN(clock_getcpuclockid, (pid_t pid, clockid_t *clock_id));
     ^
/usr/include/time.h:293:5: error: unknown type name ‘clockid_t’
 int _EXFUN(clock_setenable_attr, (clockid_t clock_id, int attr));
     ^
/usr/include/time.h:294:5: error: unknown type name ‘clockid_t’
 int _EXFUN(clock_getenable_attr, (clockid_t clock_id, int *attr));
     ^
In file included from ./sys/types.h:28:0,
                 from acl.h:24,
                 from set-acl.c:22:
/usr/include/sys/types.h:123:19: error: ‘clock_t’ redeclared as different kind of symbol
 typedef _CLOCK_T_ clock_t;
                   ^
In file included from ./time.h:41:0,
                 from /usr/include/sys/time.h:268,
                 from ./sys/time.h:39,
                 from ./sys/select.h:87,
                 from /usr/include/sys/types.h:68,
                 from ./sys/types.h:28,
                 from acl.h:24,
                 from set-acl.c:22:
/usr/include/time.h:52:1: note: previous declaration of ‘clock_t’ was here
 clock_t    _EXFUN(clock,    (void));
 ^
make[5]: *** [Makefile:2953: set-acl.lo] Error 1
make[5]: Leaving directory '/c/projects/msys2-packages/gettext/src/gettext-0.19.7/gettext-tools/gnulib-lib'
make[4]: *** [Makefile:2609: all] Error 2
make[4]: Leaving directory '/c/projects/msys2-packages/gettext/src/gettext-0.19.7/gettext-tools/gnulib-lib'
make[3]: *** [Makefile:2025: all-recursive] Error 1
make[3]: Leaving directory '/c/projects/msys2-packages/gettext/src/gettext-0.19.7/gettext-tools'
make[2]: *** [Makefile:1891: all] Error 2
make[2]: Leaving directory '/c/projects/msys2-packages/gettext/src/gettext-0.19.7/gettext-tools'
make[1]: *** [Makefile:413: all-recursive] Error 1
make[1]: Leaving directory '/c/projects/msys2-packages/gettext/src/gettext-0.19.7'
make: *** [Makefile:369: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 
[MSYS2 CI] FAILURE: gettext: Building binary failed.
 
Command exited with code 1
```

**Comment by mingwandroid** [comment]
Ah gettext had been broken by some changes to the cygwin headers...

**Comment by Alexpux** [comment]
I will commit this changes but will not rebuild all this packages

**Pull request merged**
