### PR TITLE
ninja should belongs to the base-devel group

### PR DESCRIPTION
**Pull request by ClausKlein**
Ninja is useful in combination with cmake to build sw faster than with make.

### CODE REVIEW

**Comment by ClausKlein** [comment]
We use it, and it is much faster than recursive make files!
You must not use ninja, but it is a small pkg, why not add it?

**Comment by mingwandroid** [comment]
> We use it, and it is much faster than recursive make files

I posted a link that shows basically no difference in the build-all case, can you show some stats that show otherwise?

**Comment by mingwandroid** [comment]
> You must not use ninja

I do use ninja, extensively, when CMake invokes it when I build packages that prefer Ninja. My job is as a software packager so I cannot avoid it. I don't *dislike* it though, I just question the "ninja is faster" mantra from a full-build perspective.

But I disagree with adding it to msys2-devel for a few reasons, one of which I stated above. The main reason is that these are the core packages that are expected to be installed by any MSYS2 package builder and if Ninja is always installed then CMake could find it in preference to GNU make and builds that previously worked just fine will now fail.

I can only assume that you think base-devel is something different, a handy meta-package for random software dev preferences, for example?

**Comment by ClausKlein** [comment]
Yes, base-devel was all we needed to cross compile at msys2  shell with our own proprietary tool chain.
But the ninja pkg was not available as msys2 pkg. Thats all.

**Comment by ClausKlein** [comment]
IMHO: cmake use ninja generator if requested with -G option

**Comment by mingwandroid** [comment]
> IMHO: cmake use ninja generator if requested with -G option

You do not know what can happen in the future, perhaps CMake project will decide that Ninja is a better default? Maybe some other package will find Ninja and try to use it.

I'm not totally opposed to having a ninja package in MSYS2/msys2, but we need to understand why can you not use the MSYS2/mingw-w64 one instead.

**Comment by mati865** [comment]
mingw-w64-ninja should perform better than msys/make due to being native software and using msys/ninja over mingw-w64-ninja would kill those performance gains.

The only use case for msys/ninja would be building MSYS2 packages.

**Comment by ClausKlein** [comment]
> but we need to understand why can you not use the MSYS2/mingw-w64 one instead.
that simple: cmake under mingw is completely different than cmake under msys2
try cmake --help and you will see. 
I don't linke windows, I prefere unix, possix, bash, ... and I hate "\\"

**Comment by ClausKlein** [comment]
One note about build time:
=================

klein_cl@WD002402 MINGW64 /e/workspace/tps/zlib/build
$ make clean

klein_cl@WD002402 MINGW64 /e/workspace/tps/zlib/build
$ time make
[  6%] Building C object CMakeFiles/zlib.dir/adler32.obj
[ 12%] Building C object CMakeFiles/zlib.dir/compress.obj
[ 18%] Building C object CMakeFiles/zlib.dir/crc32.obj
[ 25%] Building C object CMakeFiles/zlib.dir/deflate.obj
[ 31%] Building C object CMakeFiles/zlib.dir/inflate.obj
[ 37%] Building C object CMakeFiles/zlib.dir/infback.obj
[ 43%] Building C object CMakeFiles/zlib.dir/inftrees.obj
[ 50%] Building C object CMakeFiles/zlib.dir/inffast.obj
[ 56%] Building C object CMakeFiles/zlib.dir/trees.obj
[ 62%] Building C object CMakeFiles/zlib.dir/uncompr.obj
[ 68%] Building C object CMakeFiles/zlib.dir/zutil.obj
[ 75%] Linking C static library libzlib.a
[ 75%] Built target zlib
[ 81%] Building C object CMakeFiles/minizip.dir/contrib/minizip/ioapi.obj
[ 87%] Building C object CMakeFiles/minizip.dir/contrib/minizip/mztools.obj
[ 93%] Building C object CMakeFiles/minizip.dir/contrib/minizip/unzip.obj
[100%] Linking C static library libminizip.a
[100%] Built target minizip

real    0m4,072s
user    0m0,946s
sys     0m2,522s

klein_cl@WD002402 MINGW64 /e/workspace/tps/zlib/build
$

###########################################################

klein_cl@WD002402 MINGW64 /e/workspace/tps/zlib/build-ninja
$ ninja clean
[1/1] Cleaning all built files...
Cleaning... 16 files.

klein_cl@WD002402 MINGW64 /e/workspace/tps/zlib/build-ninja
$ time ninja
[16/16] Linking C static library libminizip.a

real    0m0,936s
user    0m1,250s
sys     0m1,853s

klein_cl@WD002402 MINGW64 /e/workspace/tps/zlib/build-ninja
$

**Comment by ClausKlein** [comment]
A second note about mingw64 tools:
=======================

klein_cl@WD002402 MINGW64 /e/workspace/tps/zlib/build-ninja
$ time ninja
[1/16] Building C object CMakeFiles/minizip.dir/contrib/minizip/ioapi.obj
FAILED: CMakeFiles/minizip.dir/contrib/minizip/ioapi.obj
C:\msys64\usr\bin\cc.exe  -I../  -MD -MT CMakeFiles/minizip.dir/contrib/minizip/ioapi.obj -MF CMakeFiles\minizip.dir\contrib\minizip\ioapi.obj.d -o CMakeFiles/minizip.dir/contrib/minizip/ioapi.obj   -c ../contrib/minizip/ioapi.c
/bin/sh: C:msys64usrbincc.exe: Kommando nicht gefunden.
[2/16] Building C object CMakeFiles/minizip.dir/contrib/minizip/mztools.obj
FAILED: CMakeFiles/minizip.dir/contrib/minizip/mztools.obj
C:\msys64\usr\bin\cc.exe  -I../  -MD -MT CMakeFiles/minizip.dir/contrib/minizip/mztools.obj -MF CMakeFiles\minizip.dir\contrib\minizip\mztools.obj.d -o CMakeFiles/minizip.dir/contrib/minizip/mztools.obj   -c ../contrib/minizip/mztools.c
/bin/sh: C:msys64usrbincc.exe: Kommando nicht gefunden.
[3/16] Building C object CMakeFiles/minizip.dir/contrib/minizip/unzip.obj
FAILED: CMakeFiles/minizip.dir/contrib/minizip/unzip.obj
C:\msys64\usr\bin\cc.exe  -I../  -MD -MT CMakeFiles/minizip.dir/contrib/minizip/unzip.obj -MF CMakeFiles\minizip.dir\contrib\minizip\unzip.obj.d -o CMakeFiles/minizip.dir/contrib/minizip/unzip.obj   -c ../contrib/minizip/unzip.c
/bin/sh: C:msys64usrbincc.exe: Kommando nicht gefunden.
[4/16] Building C object CMakeFiles/zlib.dir/adler32.obj
FAILED: CMakeFiles/zlib.dir/adler32.obj
C:\msys64\usr\bin\cc.exe  -I../  -MD -MT CMakeFiles/zlib.dir/adler32.obj -MF CMakeFiles\zlib.dir\adler32.obj.d -o CMakeFiles/zlib.dir/adler32.obj   -c ../adler32.c
/bin/sh: C:msys64usrbincc.exe: Kommando nicht gefunden.
[5/16] Building C object CMakeFiles/zlib.dir/crc32.obj
FAILED: CMakeFiles/zlib.dir/crc32.obj
C:\msys64\usr\bin\cc.exe  -I../  -MD -MT CMakeFiles/zlib.dir/crc32.obj -MF CMakeFiles\zlib.dir\crc32.obj.d -o CMakeFiles/zlib.dir/crc32.obj   -c ../crc32.c
/bin/sh: C:msys64usrbincc.exe: Kommando nicht gefunden.
[6/16] Building C object CMakeFiles/zlib.dir/compress.obj
FAILED: CMakeFiles/zlib.dir/compress.obj
C:\msys64\usr\bin\cc.exe  -I../  -MD -MT CMakeFiles/zlib.dir/compress.obj -MF CMakeFiles\zlib.dir\compress.obj.d -o CMakeFiles/zlib.dir/compress.obj   -c ../compress.c
/bin/sh: C:msys64usrbincc.exe: Kommando nicht gefunden.
[7/16] Building C object CMakeFiles/zlib.dir/deflate.obj
FAILED: CMakeFiles/zlib.dir/deflate.obj
C:\msys64\usr\bin\cc.exe  -I../  -MD -MT CMakeFiles/zlib.dir/deflate.obj -MF CMakeFiles\zlib.dir\deflate.obj.d -o CMakeFiles/zlib.dir/deflate.obj   -c ../deflate.c
/bin/sh: C:msys64usrbincc.exe: Kommando nicht gefunden.
[8/16] Building C object CMakeFiles/zlib.dir/inflate.obj
FAILED: CMakeFiles/zlib.dir/inflate.obj
C:\msys64\usr\bin\cc.exe  -I../  -MD -MT CMakeFiles/zlib.dir/inflate.obj -MF CMakeFiles\zlib.dir\inflate.obj.d -o CMakeFiles/zlib.dir/inflate.obj   -c ../inflate.c
/bin/sh: C:msys64usrbincc.exe: Kommando nicht gefunden.
[9/16] Building C object CMakeFiles/zlib.dir/infback.obj
FAILED: CMakeFiles/zlib.dir/infback.obj
C:\msys64\usr\bin\cc.exe  -I../  -MD -MT CMakeFiles/zlib.dir/infback.obj -MF CMakeFiles\zlib.dir\infback.obj.d -o CMakeFiles/zlib.dir/infback.obj   -c ../infback.c
/bin/sh: C:msys64usrbincc.exe: Kommando nicht gefunden.
[10/16] Building C object CMakeFiles/zlib.dir/inftrees.obj
FAILED: CMakeFiles/zlib.dir/inftrees.obj
C:\msys64\usr\bin\cc.exe  -I../  -MD -MT CMakeFiles/zlib.dir/inftrees.obj -MF CMakeFiles\zlib.dir\inftrees.obj.d -o CMakeFiles/zlib.dir/inftrees.obj   -c ../inftrees.c
/bin/sh: C:msys64usrbincc.exe: Kommando nicht gefunden.
ninja: build stopped: subcommand failed.

real    0m0,281s
user    0m0,090s
sys     0m0,240s

klein_cl@WD002402 MINGW64 /e/workspace/tps/zlib/build-ninja
$ which ninja
/mingw64/bin/ninja

klein_cl@WD002402 MINGW64 /e/workspace/tps/zlib/build-ninja
$ which cmake
/mingw64/bin/cmake

klein_cl@WD002402 MINGW64 /e/workspace/tps/zlib/build-ninja
$

**Comment by Alexpux** [comment]
ninja already in repo

**Pull request closed without merging**
