### PR TITLE
Add drone build script.

### PR DESCRIPTION
**Pull request by fracting**
Hi, I've setup a Wine based Drone CI server at wine-ci.org, and created build script for MSYS2-packages, could you accept this script and register your account at wine-ci.org, so I can have real data to test the Wine CI server?

### CODE REVIEW

**Comment by fracting** [comment]
BTW, with our own CI server, there is 50min of time limitation like Appveyor does, instead, we can build as long as 900 mins, configurable at Web UI in repo "settings".

**Comment by fracting** [comment]
Here is an example how the build script will work:

http://wine-ci.org/fracting/MSYS2-packages/2

Everytime when a package is touched and the commit is pushed, the CI server will clone source code from github, cd to that package directory, and call `makepkg` to build the package.

We can integrate continuous deployment in the future.
We can invent some way to trigger build by upstream change using the drone-downstream plugin in the future.

**Comment by fracting** [comment]
BTW, please ignore any 'permission error' when activate an repo in wine-ci.org, i'll try to fix that error in the drone ci server later, but that error should not prevent trigger CI builds.

The 'permission error' is a unknown (but safe) side effect when I tried to patch my own Drone CI server to downgrade github permission, see https://github.com/drone/drone/issues/1451 for more details.

**Comment by fracting** [comment]
Hi @Alexpux 

Are you able to login to http://wine-ci.org/Alexpux/MSYS2-packages and http://wine-ci.org/Alexpux/MINGW-packages, then click the 'ACTIVATE NOW' button?

Thanks!

**Comment by Alexpux** [comment]
done

**Pull request merged**
