### PR TITLE
msys2-runtime/0002-Rename-DLL-from-cygwin-to-msys.patch - Update patch

### PR DESCRIPTION
**Pull request by JPeterMugaas**
msys2-runtime/PKGBUILD - Update newlib to 2.8.1
msys2-w32api-headers/PKGBUILD - Update to latest
msys2-w32api-runtime/PKGBUILD - Update to latest

### CODE REVIEW

**Comment by Alexpux** [comment]
Revert changes with apply patch. We prefer here using git am instead patch

**Comment by JPeterMugaas** [comment]
I tried switching to git am but that only caused this:

  -> Applying 0001-Add-MSYS-triplets.patch
Applying: Add MSYS triplets.
.git/rebase-apply/patch:945: trailing whitespace.
        *-*-sco* | *-*-cygwin* | *-*-msys*)
.git/rebase-apply/patch:954: space before tab in indent.
          i[34567]86-pc-linux-*|*-*-cygwin*|*-*-msys*)
warning: 2 lines add whitespace errors.
  -> Applying 0002-Rename-DLL-from-cygwin-to-msys.patch
Applying: Rename DLL from cygwin to msys
error: winsup/cygwin/syscalls.cc.orig: does not exist in index
Patch failed at 0001 Rename DLL from cygwin to msys
The copy of the patch that failed is found in: .git/rebase-apply/patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".

and I'm not sure how to fix this.  The thing is that this is not from a git repository mailbox but a patch I personally created or adjusted.

**Comment by mati865** [comment]
`git am` already prints name of the patch so your wrapper is redundant here.

**Comment by JPeterMugaas** [comment]
I have to be honest in saying that "git am" seems to just get in my way because it fails but I get better results using the patch command.  For me, I use git after I've gotten something working and I'm satisfied with it.  In other words, it's more of an after thought.

**Comment by Alexpux** [comment]
As I tell leave git commands here.

**Pull request merged**
