### PR TITLE
Some improvement of .bat-files plus detection of ConEmu

### PR DESCRIPTION
**Pull request by Karlson2k**
Should make ConEmu users happy

### CODE REVIEW

**Comment by Alexpux** [comment]
Seems by default you try to use conemu. Don't do it

**Comment by Karlson2k** [comment]
ConEmu will be used only if it is install **and** configured as default terminal (or automatic attach is used).
If it's not acceptable, I'll implement another scheme.

Хотя мне кажется, что те, кто установил ConEmu и используют его по-умолчанию - ожидают именно такого поведения.

**Comment by Alexpux** [comment]
By default always mintty is used, no matter if ConEmu is installed.

**Comment by Karlson2k** [comment]
OK

**Comment by Karlson2k** [comment]
@Alexpux Should I update sha256sums in PKGBUILD?
Seems that I missed that in previous commits.

**Comment by Alexpux** [comment]
Yes, run "updpkgsums" and change pkgver to "2016.04" and pkgrel to 1

**Comment by Karlson2k** [comment]
@Alexpux Thanks, will do.

**Comment by Karlson2k** [comment]
Better solution: PR #538

**Pull request closed without merging**
