### PR TITLE
added patch to enable Windows SSPI authentication for msys, 2nd try

### PR DESCRIPTION
**Pull request by nightman68**
This patch enables SSPI - the Windows integrated authentication to the serf library. As result serf is using the users Kerberos TGT from the MS LSA for authentication against a kerberised Subversion server.

@dscho created the patch  originally, have a look to the [conversation](https://github.com/git-for-windows/git/issues/550).

### CODE REVIEW

**Comment by dscho** [comment]
Hrm. I see that the test failure is in *apr*, a package that was not even touched by this PR? @Alexpux What's going on with this?

**Comment by Alexpux** [comment]
Don't know. I'm not maintainer of CI systems

**Comment by nightman68** [comment]
Serf depends apr - may this is the purpose?

**Comment by mingwandroid** [comment]
Follow the commits :-)

You have a merge commit that changes a huge amount of PKGBUILDs: https://github.com/nightman68/MSYS2-packages/commit/b1384421c69b428f709b1e096920c146ce979e24

.. so the CI does what you'd hope it would. Please just create a new branch based on the very latest MSYS2-packages/master with your change on it and everything should be well.

**Comment by nightman68** [comment]
OK, I'll try.

**Comment by dscho** [comment]
@nightman68 BTW you do not need to close the PRs and open new ones, just rebase your patches and force-push the branch. That will update the PR as well.

**Comment by nightman68** [comment]
@dscho Thanks for the advice! I was not sure about that. I'm still struggle with the tools and the workflow...

**Pull request closed without merging**
