### PR TITLE
znc-git: New package

### PR DESCRIPTION
**Pull request by mattn**
made package for [znc](http://znc.in)

This will be useful to use this with irssi-git package.

### CODE REVIEW

**Comment by mattn** [comment]
Hmm, strange. In my environment, it works.

**Comment by elieux** [comment]
@mattn, maybe `autoreconf -fi` is needed?

**Comment by elieux** [comment]
Okay, so that didn't help, but replacing autoreconf with `./autogen.sh` seems to get configure past the install.sh check. Can you try this change in your environment (delete `src` before running makepkg) and amend the pull request if it succeeds?

**Comment by fracting** [comment]
@mattn Thanks for your contribution!

In order to confirm there is no false positive on the Wine CI server, I manually test the package, and found two makedepends() are missing: 'gettext-devel' and 'libsasl-devel'

(-lintl is needed when checking for Py_Initialize, maybe we need to add -lintl check in configure script as well?)

After fixing that, znc starts to build:
http://wine-ci.org/fracting/MSYS2-packages/71

**Comment by mattn** [comment]
@fracting thank you

**Comment by fracting** [comment]
@mattn could you squash three commits and `push --force`?

**Comment by fracting** [comment]
BTW, the Appveyor CI build error could be ignore in this case if I remember correctly.

@renatosilva Do you know if that's a known issue? What's the right way to solve that?
```
./configure: line 557: 0: Bad file descriptor
```
```
 557 test -n "$DJDIR" || exec 7<&0 </dev/null
```

**Comment by mattn** [comment]
squashed.

**Pull request merged**
