### PR TITLE
git-flow: upgrade to v1.12.0

### PR DESCRIPTION
**Pull request by dscho**
A new version has been released 2 days ago.

### CODE REVIEW

**Comment by dscho** [comment]
[This](https://dev.azure.com/msys2/mingw/_build/results?buildId=1220&view=logs&jobId=489142a9-7a75-504a-7680-16249a775b23&taskId=68e03a11-1cdd-5b7b-eb92-28818b701b65&lineStart=168&lineEnd=169&colStart=1&colEnd=1) is definitely not a bug introduced by this PR:

> 2019-01-20T19:02:10.2228469Z       1 [main] git-remote-https 3016 child_info_fork::abort: D:\msys32\usr\bin\msys-unistring-2.dll: Loaded to different address: parent(0x700000) != child(0x8D0000)

@Alexpux what gives?

**Comment by Alexpux** [comment]
@dscho seems it is 32 bit version is MSYS2 and this is well known situation. You need close all MSYS2 processes and run autorebase.bat batch file from MSYS2 folder

**Comment by dscho** [comment]
> seems it is 32 bit version is MSYS2 and this is well known situation. You need close all MSYS2 processes and run autorebase.bat batch file from MSYS2 folder

Yes, I know that issue from local runs. But do you need me to do anything *here*? If so, I would appreciate a clear directive. If not, please merge.

**Comment by dscho** [comment]
@Alexpux thank you for merging. Any word when this will hit the Pacman repositories?

**Comment by Alexpux** [comment]
@dscho I have very little time for MSYS2 now, so can’t say when I will do it

**Comment by Alexpux** [comment]
@dscho in repo now

**Comment by dscho** [comment]
> in repo now

Thanks a lot!

**Pull request merged**
