### PR TITLE
Add libtool patches that fixes using clang with compiler-rt and lld

### PR DESCRIPTION
**Pull request by mstorsjo**

### CODE REVIEW

**Comment by mstorsjo** [comment]
If this is ok, I can do a similar PR for MINGW-packages to add the same two patches there as well.

**Comment by mstorsjo** [comment]
Actually, one of the patches might potentially be causing issues (response files with binutils ld might need more escaping of backslashes than what is needed in linker scripts), so I'll close this PR until I've resolved my concerns around that.

**Comment by mstorsjo** [comment]
Turns out everything is fine here wrt these patches.

**Comment by Alexpux** [comment]
I think we need add this patches to mingw libtool, not msys2 one.

**Comment by mstorsjo** [comment]
I sent the pull request for the MINGW-packages repo now. Although I thought it might be valuable to have the patches here as well (as they shouldn't be harmful afaik), in case someone only has the msys version of the package installed, in use for mingw targeting (which otherwise mostly works fine for libtool, as far as I've seen).

**Pull request merged**
