### PR TITLE
Added markdown.

### PR DESCRIPTION
**Pull request by joca-bt**
Added package markdown, that converts text to markdown.

### CODE REVIEW

**Comment by elieux** [comment]
Isn't the package missing `depends`?

**Comment by joca-bt** [comment]
No, it only depends on perl, which is part of base.

**Comment by mingwandroid** [comment]
You mean base-devel? We removed perl from base (the Python developers complained :-))

**Comment by joca-bt** [comment]
Bollocks! I'll correct this tonight. Thanks and sorry.

**Comment by mingwandroid** [comment]
No problem.

**Pull request merged**
