### PR TITLE
jhbuild: mark git url as such

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by fracting** [comment]
```
+ autoreconf --verbose --force --install -Wno-portability
autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
/usr/bin/autopoint: line 485: /usr/share/gettext/archive.dir.tar.xz: No such file or directory
tar: This does not look like a tar archive
tar: gettext-0.19: Not found in archive
tar: Exiting with failure status due to previous errors
autopoint: *** infrastructure files for version 0.19 not found; this is autopoint from GNU gettext-tools 0.19.6
autopoint: *** Stop.
autoreconf: autopoint failed with exit status: 1
+ exit 1
==> ERROR: A failure occurred in build().
```
Looks like ` gettext-devel` is missing as makedepends().

**Comment by Alexpux** [comment]
Some times ago we discuss about this issue and we agree that every who develop packages for msys2/mingw-64 need install "base-devel" group to not write lots of makedepends.

**Comment by fracting** [comment]
Three days ago I made an upgrade on CI server, and it seems `base-devel` group does not include `gettext-devel` package at that time, only includes `gettext`.

```
@10892ff86b7d MSYS C:/msys32
$ pacman -S --needed --noconfirm base-devel msys2-devel mingw-w64-i686-toolchain git subversion
:: There are 51 members in group base-devel:
:: Repository msys
   1) asciidoc  2) autoconf  3) autoconf2.13  4) autogen  5) automake-wrapper
   6) automake1.10  7) automake1.11  8) automake1.12  9) automake1.13
   10) automake1.14  11) automake1.15  12) automake1.6  13) automake1.7
   14) automake1.8  15) automake1.9  16) bison  17) diffstat  18) diffutils
   19) dos2unix  20) file  21) flex  22) gawk  23) gdb  24) gettext  25) gperf
   26) grep  27) groff  28) help2man  29) intltool  30) lemon  31) libtool
   32) libunrar  33) m4  34) make  35) man-db  36) pacman  37) patch
   38) patchutils  39) perl  40) pkg-config  41) pkgfile  42) rcs  43) scons
   44) sed  45) swig  46) texinfo  47) texinfo-tex  48) ttyrec  49) unrar
   50) wget  51) xmlto
```

Is there anything changed in the passed three days, or it is there a mistake?

Thanks!

**Comment by Alexpux** [comment]
Ok seems gettext-devel placed into "development" group instead. will fix it shortly

**Pull request merged**
