### PR TITLE
Add futureware mirror

### PR DESCRIPTION
**Pull request by nickoe**
Sponsored by Sourcerer

### CODE REVIEW

**Comment by svnpenn** [comment]
#221

**Comment by svnpenn** [comment]
You might want to tap the brakes on HTTPS

~~~
www2.futureware.at uses an invalid security certificate. The certificate is not
trusted because the issuer certificate is unknown.
(Error code: sec_error_unknown_issuer)
~~~

**Comment by svnpenn** [comment]
@Alexpux you might want to tap the brakes on HTTPS

~~~
www2.futureware.at uses an invalid security certificate. The certificate is not
trusted because the issuer certificate is unknown.
(Error code: sec_error_unknown_issuer)
~~~

**Comment by nickoe** [comment]
@svnpenn What exactly is the issue here? Why does this matter for a mirror?

When I test your commands for the futureware mirror I get times usually around 120 to 180 ms on http, and 280 to 300 on https.  Not a big deal.  I don't know why you need to use the spider option with https, is this something pacman does?

**Comment by Alexpux** [comment]
Pacman use ````libcurl```` that use ````p11-kit```` to check certificates for remote host. We have ````ca-certificates```` package that contain trusted certificates.

**Comment by svnpenn** [comment]
@nickoe perhaps look at my previous comment carefully

~~~
ERROR: The certificate of ‘www2.futureware.at’ is not trusted.
ERROR: The certificate of ‘www2.futureware.at’ hasn't got a known issuer.
~~~

**Comment by nickoe** [comment]
Why does this matter for pacman?

**Comment by Alexpux** [comment]
because it can reject downloading from it if certificate is bad.

**Comment by svnpenn** [comment]
@nickoe could you host Base also? As has been said, SourceForge is horrible and if I can avoid it completely, I will.

http://sourceforge.net/projects/msys2/files/Base

**Comment by svnpenn** [comment]
https://github.com/Alexpux/MSYS2-packages/pull/357

**Comment by svnpenn** [comment]
https://github.com/Alexpux/MSYS2-packages/issues/296

**Comment by svnpenn** [comment]
https://github.com/Alexpux/MSYS2-packages/issues/163

**Pull request merged**
