### PR TITLE
Update Python3 to 3.6.1 version

### PR DESCRIPTION
**Pull request by PiotrVV**

### CODE REVIEW

**Comment by Alexpux** [comment]
Why so many new patches?

**Comment by PiotrVV** [comment]
Because I write packages that are most compatible with many different platforms.

**Comment by PiotrVV** [comment]
I only added compatibility with the arm platform.

**Comment by PiotrVV** [comment]
Prepares python for the new msys-runtime version with many fixes for the arm platform

**Comment by Alexpux** [comment]
In few days 3.6.2 will be released

**Comment by gerryqd** [comment]
An issue related to this upgrade is that, the  python3-setuptools is not upgraded yet.
That causes problems!

Please help to fix it.

**Comment by PiotrVV** [comment]
Correct order of building modules:
python-appdirs
python-colorama
python-packaging
python-pygments
python-pyparsing
python-six
python-setuptools

**Pull request merged**
