### PR TITLE
gnupg2 for MSYS2

### PR DESCRIPTION
**Pull request by andrew-grechkin**
* update libgpg-error
* update libgcrypt
* update libassuan
* update pinentry
* update gnupg

! pinentry by default uses w32 app (gui window)
  whoever wants console pinentry should use pinentry-mode=loopback
! dirmngr uses system dns resolver but not libdns (fixes problems with keyserver unaccessable)
! libgcrypt patched and built with options preventing segfaults

### CODE REVIEW

**Comment by Alexpux** [comment]
Previously we discuss about gnupg2. It not properly work for MSYS2. Try yourself using it for signing packages with makepkg

**Comment by Alexpux** [comment]
@andrew-grechkin do you try gnupg2 yourself under MSYS2 ? Does it work correctly with signing packages at least?

**Comment by Alexpux** [comment]
@andrew-grechkin read https://github.com/Alexpux/MSYS2-packages/issues/859

**Comment by andrew-grechkin** [comment]
@Alexpux 
sorry didn't get what should be wrong with makepkg. Signing with makepkg works correctly.
The problem is only with old pacman using old gnupg which cannot check signature. But this means only that pacman should be updated

~/git/public/msys2/MSYS2-packages/pinentry ag/gnupg2$ gpg --version
gpg (GnuPG) 2.2.8-unknown
libgcrypt 1.8.2

~/git/public/msys2/MSYS2-packages/pinentry ag/gnupg2$ makepkg -sC --skippgpcheck --sign
==> Making package: pinentry 1.1.0-1 (Fri, Jun 22, 2018  8:08:13 AM)
...
==> Tidying install...
  -> Removing libtool files...
  -> Purging unwanted files...
  -> Stripping unneeded symbols from binaries and libraries...
  -> Compressing man and info pages...
==> Checking for packaging issue...
==> Creating package "pinentry"...
  -> Generating .PKGINFO file...
  -> Generating .BUILDINFO file...
  -> Adding install file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Signing package...
  -> Created signature file /c/Users/andrew/git/public/msys2/MSYS2-packages/pinentry/pinentry-1.1.0-1-x86_64.pkg.tar.xz.sig.
==> Finished making: pinentry 1.1.0-1 (Fri, Jun 22, 2018  8:09:07 AM)

~/git/public/msys2/MSYS2-packages/pinentry ag/gnupg2$ gpg --verify pinentry-1.1.0-1-x86_64.pkg.tar.xz.sig
gpg: assuming signed data in 'pinentry-1.1.0-1-x86_64.pkg.tar.xz'
gpg: Signature made Fri, Jun 22, 2018  8:08:50 AM CEST
gpg:                using RSA key 3B3605C3C0BAEB0D02808F3F4D529F9074C30A4F
gpg: Good signature from "Andrew Grechkin <andrew.grechkin@gmail.com>" [ultimate]
gpg:                 aka "Andrei Grechkin <andrei.grechkin@booking.com>" [ultimate]

**Comment by andrew-grechkin** [comment]
@Alexpux the problem with test is that these packages are interpendant on each other and should be built in proper order which is in PR comment

**Comment by Alexpux** [comment]
@andrew-grechkin I know about order. I ask to remove them because I already build them locally and push changes to my repo

**Comment by Alexpux** [comment]
@andrew-grechkin You remove libgpg-error and libgcrypt PKGBUILDs in your pull request. Fix it

**Comment by andrew-grechkin** [comment]
@Alexpux  done

**Comment by Alexpux** [comment]
@andrew-grechkin also dont include changes for some packages in one commit. One commit - one package, this will help a lot to tracking changes

**Comment by andrew-grechkin** [comment]
@Alexpux  I know about the rule but in current situation is kinda exception because all this packages need to be updated to be able to build properly

**Comment by Alexpux** [comment]
@andrew-grechkin there are no exception. Your pull request just will contain some commits. Also you still not fix issue with removing libgpg-error anf libgcrypt

**Comment by Alexpux** [comment]
@andrew-grechkin I'm closing pull request and will do myself

**Comment by Alexpux** [comment]
@andrew-grechkin I'm build gnupg2 but it still not work properly.
When sign package now I see pinentry window where need to enter passphrase. But after entering password I get error:
````
==> Making package: gnupg 2.2.8-1 (Fri Jun 22 10:42:02 2018)
==> Retrieving sources...
  -> Found gnupg-2.2.8.tar.bz2
  -> Found gnupg-2.2.8.tar.bz2.sig
  -> Found gnupg-2.2.8-msys2.patch
==> WARNING: Skipping verification of source file PGP signatures.
==> Validating source files with sha256sums...
    gnupg-2.2.8.tar.bz2 ... Passed
    gnupg-2.2.8.tar.bz2.sig ... Skipped
    gnupg-2.2.8-msys2.patch ... Passed
==> Creating source package...
  -> Adding PKGBUILD...
  -> Generating .SRCINFO file...
  -> Adding gnupg-2.2.8.tar.bz2...
  -> Adding gnupg-2.2.8.tar.bz2.sig...
  -> Adding gnupg-2.2.8-msys2.patch...
  -> Adding install file (gnupg.install)...
  -> Compressing source package...
==> Signing package...
==> WARNING: Failed to sign package file.

==> ERROR: An unknown error has occurred. Exiting...
User defined signal 1
````

**Comment by andrew-grechkin** [comment]
@Alexpux  I did removed requested files.
Which version of gnupg you have installed in your system at the moment of building and signing package from your failing example?

**Comment by Alexpux** [comment]
@andrew-grechkin 2.2.8

**Comment by Alexpux** [comment]
@andrew-grechkin I will upload all packages updates except gnupg2 itself in 15 min. UYou can try to build gnupg2 with makepkg ang try sign it

**Comment by andrew-grechkin** [comment]
@Alexpux 
I rechecked again - when i have below packages installed and .gnupg db generated by gpg v2 everything works ok. Need to check with .gnupg made by gpg v1.
pacman -Syu
warning: gnupg: local (2.2.8-1) is newer than msys (1.4.22-3)
warning: libassuan: local (2.5.1-1) is newer than msys (2.4.3-1)
warning: libassuan-devel: local (2.5.1-1) is newer than msys (2.4.3-1)
warning: libgcrypt: local (1.8.2-1) is newer than msys (1.8.1-1)
warning: libgcrypt-devel: local (1.8.2-1) is newer than msys (1.8.1-1)
warning: libgpg-error: local (1.31-1) is newer than msys (1.27-1)
warning: libgpg-error-devel: local (1.31-1) is newer than msys (1.27-1)
warning: pinentry: local (1.1.0-1) is newer than msys (0.9.7-1)

**Comment by andrew-grechkin** [comment]
@Alexpux  don't upload anything to db yet. I cant be to active and respond momentary on this - i'm at work

**Comment by Alexpux** [comment]
@andrew-grechkin  what you mean don't upload?

**Comment by Alexpux** [comment]
Maybe need reinitializee msys2-keyring with gnupg2 before using it

**Comment by andrew-grechkin** [comment]
@Alexpux  I installed clean msys2 with packages from public repo, 
built gnugp2 and confirm it is not for working for me either, i see segfaults when even gpg --list-keys.
But as soon I installed packages I built myself (here ftp://andrew-grechkin.dynu.net/msys2)- everything is working.

**Comment by andrew-grechkin** [comment]
@Alexpux  i see you merged the libgcrypt with not all my changes - that is the reason. I made some options to .configure that were fixing the segfaults.

**Comment by Alexpux** [comment]
@andrew-grechkin seems building libgcrypt without asm did the trick

**Comment by andrew-grechkin** [comment]
@Alexpux glad to here that
there are pacman and gpgme that also should be rebuilt (maybe something else) and this packaged should be updated all together with gnupg not separately - otherwise pacman ability to check signatures is broken

**Comment by Alexpux** [comment]
@andrew-grechkin I'm upload 64 bit packages. You can try if everything work

**Pull request closed without merging**
