### PR TITLE
emacs-nox for msys2

### PR DESCRIPTION
**Pull request by RickLeaf**
emacs without x tool kit version for MSYS2

### CODE REVIEW

**Comment by mati865** [comment]
I think naming it `emacs` instead of emacs-nox would be better.
Also check CI error:
```
configure: error: You seem to be running X, but no X development libraries
were found.  You should install the relevant development files for X
and for the toolkit you want, such as Gtk+ or Motif.  Also make
sure you have development files for image handling, i.e.
tiff, gif, jpeg, png and xpm.
If you are sure you want Emacs compiled without X window support, pass
  --without-x
to configure.
```

**Comment by RickLeaf** [comment]
This package is for MSYS2 environment like vim.

**Comment by RickLeaf** [comment]
msys2 do not include x tool kit, if we use it with GUI, we must use WIN32 native GUI solution. But we have full emacs for win32 version in mingw.

**Comment by RickLeaf** [comment]
makepkg --skippgpcheck   in your MSYS

**Comment by elieux** [comment]
@RickLeaf, the mingw version is named `mingw-w64-i686-emacs` or `mingw-w64-x86_64-emacs` in pacman.

**Comment by RickLeaf** [comment]
@elieux yes, I knew. I have used it for a long time.

**Comment by elieux** [comment]
Then why not use the name `emacs` for msys2 emacs?

Anyway, that's just a nitpick. More important is to solve the CI error. I think you just need to add `--without-x` to the `./configure` line.

**Comment by RickLeaf** [comment]
Ok , I rename it

**Pull request closed without merging**
