### PR TITLE
iperf: New package (2.0.10)

### PR DESCRIPTION
**Pull request by Equim-chan**

### CODE REVIEW

**Comment by sskras** [comment]
Can someone please explain, why it went into MSYS2-packages ant into MINGW-packages ?

**Comment by Alexpux** [comment]
I don't want to increase MSYS2 packages list without any good reason. MSYS2 goal is to build MINGW packages

**Comment by sskras** [comment]
@Alexpux , it's very wise decision.  I fixed my question.  What are the reason to put iperf2 into MSYS2?  I guess no package in the world does need iperf.  Correct me if I am wrong, please.

**Comment by Alexpux** [comment]
@sskras where you see iperf2 package? I dont add it.

**Comment by sskras** [comment]
Ah, OK then.  I mixed up a commit from in PR (from @Equim-chan) with an official commit (in public repo).  Thanks @Alexpux for clarification.  I still need to get used to GitHub:)

**Pull request closed without merging**
