### PR TITLE
bash: Add missing build dependencies

### PR DESCRIPTION
**Pull request by dscho**
Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>

### CODE REVIEW

**Comment by Alexpux** [comment]
In this case you need add such dependencies to EVERY package. We decide to not do it as for develop packages you need install ````base-devel```` group of packages in any case.

**Comment by dscho** [comment]
Ah, okay. I just thought that maybe for the most commonly to-be-rebuilt packages (such as msys2-runtime and bash) it would make sense to make it easier for contributors who do not know about that `base-devel` thing (I, for one, did not)...

**Comment by elieux** [comment]
Just adding some info for the curious.

The implicit dependency on `base-devel` is documented on our [Buliding packages](https://sourceforge.net/p/msys2/wiki/Contributing%20to%20MSYS2/) wikipage and it's a heritage from Arch Linux (documented on [Creating packages](https://wiki.archlinux.org/index.php/Creating_packages) on the ArchWiki). Upstream [FS#11766](https://bugs.archlinux.org/task/11766) describes some reasons for the current state of things -- why there's no check in makepkg a why PKGBUILDs omit these dependencies.

**Comment by dscho** [comment]
Here's an idea: why not just teaching `makepkg -s` to add that dependency implicitly? (And the equivalent dependency on the toolchain with `makepkg-mingw -s`?) Then nobody would need to be puzzled, and the documentation would also be unnecessary...

**Pull request closed without merging**
